#!/bin/bash

######################################################################################################
#These two commands will check for updates and install the prerequisites requires to start the process
apt-get update
apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make
######################################################################################################

######################################################################################################
#cd ~ will send the user to their home directory and the git clone commands will download the 
#necessary repositories requires for kernel compilation
#cd ~
git clone --depth=1 https://github.com/raspberrypi/linux || ( cd ./linux && git pull ) 
git clone --depth=1 https://github.com/s3728823/s3728823-student-rmit.edu.au

######################################################################################################
#mv command will move the .config file from my repository to the users newly downloaded linux folder
#mv ~/.config ~/linux
cd ./linux
######################################################################################################

KERNEL=kernel7

make bcm2709_defconfig
make -j4 zImage modules dtbs
make modules_install

cp arch/arm/boot/dts/*.dtb /boot/
cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
cp arch/arm/boot/dts/overlays/README /boot/overlays/
cp arch/arm/boot/zImage /boot/$KERNEL.img

echo "Hello World"
