#!/bin/bash
#####################################################################################################
###################		George Kalaitzakis s3728823			#####################
#####################################################################################################
#Simple script to display CPU temperature when build_kernel bash script is running
echo "Hello build_kernel!"

printf "-15s%5s\n" "TIMESTAMP" "TEMP(degC)" #printf ensures that the temperature it outputs will be formatted appropriately
printf "%20s\n" "....................."

while true
do
temp=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
timestamp=$(date +'%s')
printf "%-15s%5s\n" "Stimestamp" "$temp"
sleep 1
done

