#!/bin/bash
#####################################################################################################
###################		George Kalaitzakis s3728823			#####################
#####################################################################################################
echo "Hello World"

printf "-15s%5s\n" "TIMESTAMP" "TEMP(F)"
printf "%20s\n" "....................."

while true
do
tempC=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
tempF=$(echo "scale=2; 1.8 *$tempC + 32" | bc)
timestamp=$(date +'%s')
printf "%-15s%5s\n" "$timestamp" "$tempF"
sleep 1

done
